package com.consultancy.education.service;

import com.consultancy.education.DTOs.requestDTOs.studentCollegeCourseRegistration.StudentCollegeCourseRegistrationEditRequestDto;
import com.consultancy.education.DTOs.requestDTOs.studentCollegeCourseRegistration.StudentCollegeCourseRegistrationRequestDto;
import com.consultancy.education.DTOs.responseDTOs.studentCollegeCourseRegistration.StudentCollegeCourseRegistrationResponseDto;

import java.util.List;

public interface StudentCollegeCourseRegistrationService {

    StudentCollegeCourseRegistrationResponseDto registerStudentForCourse(StudentCollegeCourseRegistrationRequestDto request);

    StudentCollegeCourseRegistrationResponseDto editRegistration(StudentCollegeCourseRegistrationEditRequestDto requestDto);

    StudentCollegeCourseRegistrationResponseDto getRegistrationById(Long registrationId);

    List<StudentCollegeCourseRegistrationResponseDto> getRegistrationsByStudentId(Long studentId);

    StudentCollegeCourseRegistrationResponseDto submitRegistration(Long registrationId);
}
